/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-17 08:26:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Reset */\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Body and Layout */\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("      background-color: #f4f6f9;\r\n");
      out.write("      color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Navbar */\r\n");
      out.write("    .navbar {\r\n");
      out.write("      background-color: #2d3e50;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 1rem 2rem;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("      font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      margin-left: 1rem;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      transition: color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a:hover {\r\n");
      out.write("      color: #00c7ae;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Main Dashboard */\r\n");
      out.write("    .dashboard {\r\n");
      out.write("      padding: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .welcome-box {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 1.5rem;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      margin-bottom: 2rem;\r\n");
      out.write("      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-section,\r\n");
      out.write("    .progress-section {\r\n");
      out.write("      margin-bottom: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-cards {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 1rem;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-card {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 1rem;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      width: 250px;\r\n");
      out.write("      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-card h4 {\r\n");
      out.write("      margin-bottom: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-card button {\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      background-color: #00c7ae;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border: none;\r\n");
      out.write("      padding: 0.6rem 1.2rem;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background-color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quiz-card button:hover {\r\n");
      out.write("      background-color: #019e8e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .score-list {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 1rem;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .score-list li {\r\n");
      out.write("      margin-bottom: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 1rem;\r\n");
      out.write("      background-color: #2d3e50;\r\n");
      out.write("      color: white;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .quiz-card input{\r\n");
      out.write("    	display: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write(" <header class=\"navbar\">\r\n");
      out.write("    <h1 class=\"logo\">QuizMaster</h1>\r\n");
      out.write("    <nav class=\"nav-links\">\r\n");
      out.write("      <a href=\"welcome.jsp\">Dashboard</a>\r\n");
      out.write("      <a href=\"availablequizzes.html\">Quizzes</a>\r\n");
      out.write("      <a href=\"#\">Past Results</a>\r\n");
      out.write("      <a href=\"quizmaster.html\">Logout</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"dashboard\">\r\n");
      out.write("    <section class=\"welcome-box\">\r\n");
      out.write("      <h2>Welcome, ");
      out.print( (String)request.getAttribute("fName") );
      out.write(" 👋</h2>\r\n");
      out.write("      <p>Ready to test your knowledge? Choose a quiz below!</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"quiz-section\">\r\n");
      out.write("      <h3>Available Quizzes</h3>\r\n");
      out.write("      <div class=\"quiz-cards\">\r\n");
      out.write("        <form action=\"startQuiz\" method=\"GET\">\r\n");
      out.write("          <div class=\"quiz-card\">\r\n");
      out.write("            <h4>Java Basics</h4>\r\n");
      out.write("            <p>Questions | Easy</p>\r\n");
      out.write("            <input value=\"Java\" name=\"examType\" />\r\n");
      out.write("            <button type=\"submit\">Start Quiz</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <form action=\"startQuiz\" method=\"GET\">\r\n");
      out.write("          <div class=\"quiz-card\">\r\n");
      out.write("          <h4>ORACLE</h4>\r\n");
      out.write("          <p>Questions | Medium</p>\r\n");
      out.write("          <input value=\"ORACLE\" name=\"examType\" />\r\n");
      out.write("          <button>Start Quiz</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"startQuiz\" method=\"GET\">\r\n");
      out.write("          <div class=\"quiz-card\">\r\n");
      out.write("          <h4>Data Structures</h4>\r\n");
      out.write("          <p>Questions | Hard</p>\r\n");
      out.write("          <input value=\"DS\" name=\"examType\" />\r\n");
      out.write("          <button>Start Quiz</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"progress-section\">\r\n");
      out.write("      <h3>Your Recent Scores</h3>\r\n");
      out.write("      <ul class=\"score-list\">\r\n");
      out.write("        <li><strong>Java Basics:</strong> 80%</li>\r\n");
      out.write("        <li><strong>Oracle:</strong> 90%</li>\r\n");
      out.write("        <li><strong>Data Structures:</strong> 65%</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <p>&copy; 2025 QuizMaster | Made with 💡 by Prabhanjan Amanta.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
